### ISSUE TITLE
Соединение установленно/прервано

### ISSUE THREAD

**Issue by salomanov** [WonderCRM/CRMui3#10]
Здравствуйте, собирается проект с использованием вашей оболочки, подскажите пожалуйста у меня часто устанавливается и прерывается соединение. Что на это может влиять, я новичок и не совсем понимаю что за это отвечает. Спасибо

**Comment by WonderCRM** [comment]
> Здравствуйте, собирается проект с использованием вашей оболочки, подскажите пожалуйста у меня часто устанавливается и прерывается соединение. Что на это может влиять, я новичок и не совсем понимаю что за это отвечает. Спасибо

Здравствуйте, много что может влиять, конфликт библиотек, баги, плохо написанный код и т.д.
