### ISSUE TITLE
WiFi client mode

### ISSUE THREAD

**Issue by JavaStarter** [WonderCRM/CRMui3#3]
Hi
I can't switch WIFI to client mode.
I find the Wi-Fi network, select and enter the password, I see in the terminal that the settings are saved, but after restarting ESP module, the AP mode returns.

Привет
Не могу переключить WIFI в режим клиента, для подключения к моему роутеру.
Я нахожу свою сеть, выбираю её, ввожу пароль. В терминале я вижу что изменения применяются и конфигурация сохраняется, но после перезагрузки модуля он снова поднимает свою WiFi AP на адресе 192.168.4.1, а к роутеру не пытается подключиться.

**Comment by WonderCRM** [comment]
> Привет
> Не могу переключить WIFI в режим клиента, для подключения к моему роутеру.
> Я нахожу свою сеть, выбираю её, ввожу пароль. В терминале я вижу что изменения применяются и конфигурация сохраняется, но после перезагрузки модуля он снова поднимает свою WiFi AP на адресе 192.168.4.1, а к роутеру не пытается подключиться.

Привет, точка доступа поднимается в любом режиме принудительно, и отключается после успешного подключения если установлен режим работы Клиент. Проверьте введённые данные. Также в IDE можно выставить режим дебага на Verbose, чтобы понять что происходит.
