### ISSUE TITLE
Не собирается проект через Platformio для ESP32

### ISSUE THREAD

**Issue by Doctormegabit** [WonderCRM/CRMui3#7]
собственно не хочет собираться, ошибок по зависимостям нет. 
c:/users/sergey/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\node32s\libaaa\libESPAsyncWebServer.a(AsyncWebSocket.cpp.o):(.literal._ZN22AsyncWebSocketResponseC2ERK6StringP14AsyncWebSocket+0x10): undefined reference to `SHA1Init'
c:/users/sergey/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\node32s\libaaa\libESPAsyncWebServer.a(AsyncWebSocket.cpp.o):(.literal._ZN22AsyncWebSocketResponseC2ERK6StringP14AsyncWebSocket+0x14): undefined reference to `SHA1Update'
c:/users/sergey/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\node32s\libaaa\libESPAsyncWebServer.a(AsyncWebSocket.cpp.o):(.literal._ZN22AsyncWebSocketResponseC2ERK6StringP14AsyncWebSocket+0x18): undefined reference to `SHA1Final'
c:/users/sergey/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\node32s\libaaa\libESPAsyncWebServer.a(AsyncWebSocket.cpp.o): in function `AsyncWebSocketResponse::AsyncWebSocketResponse(String const&, AsyncWebSocket*)':
C:\Users\Sergey\Nextcloud2\IoT\ESP32\FAN_CRMUI/lib/ESPAsyncWebServer/src/AsyncWebSocket.cpp:1365: undefined reference to `SHA1Init'
c:/users/sergey/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Sergey\Nextcloud2\IoT\ESP32\FAN_CRMUI/lib/ESPAsyncWebServer/src/AsyncWebSocket.cpp:1366: undefined reference to `SHA1Update'
c:/users/sergey/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Sergey\Nextcloud2\IoT\ESP32\FAN_CRMUI/lib/ESPAsyncWebServer/src/AsyncWebSocket.cpp:1367: undefined reference to `SHA1Final'
c:/users/sergey/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\node32s\libaaa\libESPAsyncWebServer.a(WebAuthentication.cpp.o):(.literal._ZL6getMD5PhtPc+0x8): undefined reference to `mbedtls_md5_starts'
c:/users/sergey/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\node32s\libaaa\libESPAsyncWebServer.a(WebAuthentication.cpp.o): in function `getMD5(unsigned char*, unsigned short, char*)':
C:\Users\Sergey\Nextcloud2\IoT\ESP32\FAN_CRMUI/lib/ESPAsyncWebServer/src/WebAuthentication.cpp:79: undefined reference to `mbedtls_md5_starts'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\node32s\firmware.elf] Error 1

для 8266 собирает, а esp32 какие я только параметры не ставил

**Comment by WonderCRM** [comment]
Попробуйте на последней версии.
