### ISSUE TITLE
В Arduino IDE 2.0 выводит некорректное предупреждение при компиляции

### ISSUE THREAD

**Issue by rvbglas** [WonderCRM/CRMui3#8]
"ПРЕДУПРЕЖДЕНИЕ: библиотека CRMui3 должна запускаться на архитектурах ESP8266, ESP32 и может быть несовместима с вашей платой на архитектуре esp8266."

Похоже, с заглавных на строчные переделали. Некритично, но глаза мозолит.

**Comment by WonderCRM** [comment]
Поправил. Спасибо
