### ISSUE TITLE
Library for WiFi-CLOCK

### ISSUE THREAD

**Issue by FrankHovis** [WonderCRM/CRMui3#9]
The source for WIFI CLOCK needs these libraries

#include "CRMui.h"
#include "CRM_Time.h"

Where can I download them?

**Comment by WonderCRM** [comment]
What project is this from?

**Comment by FrankHovis** [comment]
https://cloud.mail.ru/public/5eHE/dCHUyqrr1 and https://github.com/WonderCRM/wondercrm.github.io

**Comment by CrmDev** [comment]
https://cloud.mail.ru/public/5eHE/dCHUyqrr1/WiFi-RELE/Source.rar

**Comment by FrankHovis** [comment]
Thanks, but it seems the release source is incomplete, there's no clock display or code to do such.

**Comment by WonderCRM** [comment]
The source code of WiFi-CLOCK 2 is not in the public domain.
